### ISSUE TITLE
Link to repo

### ISSUE THREAD

**Issue by Gudahtt** [MUNComputerScienceSociety/Website#5]
Should we have a link to the repository anywhere on the website? Does one exist already that I missed?

A 'Fork me on Github!' thing might be a bit much, but it couldn't hurt to tell people how they can contribute.

**Comment by ranguli** [comment]
Not exactly what you're looking for, but I've added a link to the GitHub page, #17

**Comment by jackharrhy** [comment]
https://github.com/MUNComputerScienceSociety/Website/pull/22
