### ISSUE TITLE
Replace embedded IRC client with HTTPS compatible client

### ISSUE THREAD

**Issue by Gudahtt** [MUNComputerScienceSociety/Website#8]
The current embedded web irc client doesn't work, as it isn't compatible with HTTPS. It should be replaced with an embedded HTTPS web client.

**Comment by Manouchehri** [comment]
How about migrating the channel to Freenode and using their web UI?

**Comment by Gudahtt** [comment]
Yep, that is likely what we'll do. They're having a discussion about whether to move soon.

**Comment by Gudahtt** [comment]
This was completed by @eeshangarg recently
